name: Deploy
on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - src/**
      - public/**
      - package.json
    branches:
      - "main"
      - "stable"
  workflow_dispatch:

jobs:
  prod:
    name: Production
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/stable'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci --ignore-scripts
      - run: npm run deploy:prod -- -r https://git:${DEPLOYMENT_PAT}@github.com/thetolproject/thetolproject.github.io.git -u "${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
        env:
          DEPLOYMENT_PAT: ${{ secrets.DEPLOYMENT_PAT }}

  dev:
    name: Development
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci --ignore-scripts
      - run: npm run deploy:dev -- -r https://git:${DEPLOYMENT_PAT}@github.com/PoliNetworkOrg/TheTOLProject.git -u "${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
        env:
          DEPLOYMENT_PAT: ${{ github.token }}
