name: Deploy
on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - src/**
  workflow_dispatch:

jobs:
  gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci --ignore-scripts
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run deploy -- -u "${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
