name: Deploy
on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - src/**
      - public/**
      - package.json
    branches:
      - "main"
  release:
    types: [published]
  workflow_dispatch:

jobs:
  gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci --ignore-scripts
      - run: npm run deploy -- -r https://${DEPLOYMENT_PAT}@github.com/thetolproject/thetolproject.github.io.git -u "${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
        env:
          DEPLOYMENT_PAT: ${{ secrets.DEPLOYMENT_PAT }}
