name: Release
on:
  release:
    types: [published]

jobs:
  prod:
    name: Deploy production
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run deploy:prod -- -r https://git:${DEPLOYMENT_PAT}@github.com/thetolproject/thetolproject.github.io.git -u "${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
        env:
          DEPLOYMENT_PAT: ${{ secrets.DEPLOYMENT_PAT }}

  tags:
    name: Update tags
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: EndBug/latest-tag@v1
        with:
          ref: stable
